In [29]:
def calculate_impedance(components, connection_type='series'):
    """
    Calculates total impedance for a list of complex impedance values.

    :param components: List of complex numbers (e.g., [10+0j, 0-5j])
    :param connection_type: 'series' or 'parallel'
    :return: Total complex impedance
    """
    if not components:
        return 0

    if connection_type.lower() == 'series':

        return sum(components)

    elif connection_type.lower() == 'parallel':

        reciprocal_sum = sum(1 / z for z in components if z != 0)
        return 1 / reciprocal_sum if reciprocal_sum != 0 else 0

    else:
        raise ValueError("Connection type must be 'series' or 'parallel'")




circuit_elements = [100 + 0j, 0 + 50j, 0 - 30j]


z_series = calculate_impedance(circuit_elements, 'series')
z_parallel = calculate_impedance(circuit_elements, 'parallel')

print(f"Components: {circuit_elements}")
print(f"Total Series Impedance: {z_series} Ohms")
print(f"Total Parallel Impedance: {z_parallel:.2f} Ohms")
print(f"Magnitude (Series): {abs(z_series):.2f} Ohms")


Components: [(100+0j), 50j, -30j]
Total Series Impedance: (100+20j) Ohms
Total Parallel Impedance: 36.00-48.00j Ohms
Magnitude (Series): 101.98 Ohms


In [31]:
import numpy as np
stock_a = np.array([
    [150.20, 155.00, 149.50],
    [154.50, 158.20, 153.10],
    [157.00, 159.00, 156.50],
    [158.10, 162.50, 157.80],
    [161.00, 165.00, 160.20]
])

stock_b = np.array([
    [145.00, 148.50, 144.20],
    [147.20, 150.00, 146.50],
    [149.50, 152.10, 148.80],
    [151.00, 155.30, 150.00],
    [153.50, 158.00, 152.90]
])


combined_prices = np.add(stock_a, stock_b)


price_spread = np.subtract(stock_a, stock_b)


print("--- Combined Stock Prices (Sum) ---")
print(combined_prices)

print("\n--- Daily Price Spread (Difference: A - B) ---")
print(price_spread)

--- Combined Stock Prices (Sum) ---
[[295.2 303.5 293.7]
 [301.7 308.2 299.6]
 [306.5 311.1 305.3]
 [309.1 317.8 307.8]
 [314.5 323.  313.1]]

--- Daily Price Spread (Difference: A - B) ---
[[5.2 6.5 5.3]
 [7.3 8.2 6.6]
 [7.5 6.9 7.7]
 [7.1 7.2 7.8]
 [7.5 7.  7.3]]
